.nix:
  image: registry.gitlab.com/cynerd/gitlab-ci-nix
  tags:
    - docker
  cache:
    key: "nix"
    paths:
      - ".nix-cache"
  before_script:
    - gitlab-ci-nix-cache-before
  after_script:
    - gitlab-ci-nix-cache-after

stages:
  - build
  - release

backend-build:
  extends: .nix
  stage: build
  script:
    - nix build .#backend

frontend-build:
  extends: .nix
  stage: build
  script:
    - echo VITE_REQUEST_URL=$VITE_REQUEST_URL >> frontend/.env
    - echo VITE_API_TOKEN=$VITE_API_TOKEN >> frontend/.env
    - cat frontend/.env
    - nix build .#frontend

docker-build:
  extends: .nix
  stage: build
  needs:
    - backend-build
    - frontend-build
  artifacts:
    paths:
      - blcc-image.tar.gz
  script:
    - nix build
    - cp result blcc-image.tar.gz

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

release-image:
  image: docker:26.1.3
  stage: release
  needs:
    - docker-build
  tags:
    - dind
  services:
    - docker:26.1.3-dind
  dependencies:
    - docker-build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker load < blcc-image.tar.gz
    - docker tag blcc:latest $IMAGE_TAG
    - docker push $IMAGE_TAG