stages:
  - build
  - docker
  - deploy

backend-build:
  image: clux/muslrust:1.85.0-nightly
  stage: build
  script:
    - cd backend
    - rustup target add "x86_64-unknown-linux-musl"
    - cargo build --release --locked --target "x86_64-unknown-linux-musl"
  cache:
    - key:
        files:
          - backend/Cargo.lock
      paths:
        - backend/target
  artifacts:
    paths:
      - backend/target/x86_64-unknown-linux-musl/release/backend

frontend-build:
  image: node:23
  stage: build
  before_script:
    - cd frontend
    - corepack enable pnpm
    - pnpm config set @lrd:registry=$CI_API_V4_URL/projects/$E3_SDK_PROJECT_ID/packages/npm/
    - pnpm config set //gitlab.nist.gov/gitlab/api/v4/projects/$E3_SDK_PROJECT_ID/packages/npm/:_authToken="$E3_SDK_PROJECT_TOKEN"
    - pnpm config list
  script:
    - pnpm install
    - pnpm run build
  cache:
    - key:
        files:
          - frontend/pnpm-lock.yaml
      paths:
        - frontend/node_modules
  artifacts:
    paths:
      - frontend/dist/*

include:
  - component: $CI_SERVER_FQDN/ELDST/ci-components/docker-build@1.1.0
  - component: $CI_SERVER_FQDN/ELDST/ci-components/portainer-deploy@1.1.0
    inputs:
      url: haproxy-p.el.nist.gov:9000
      name: blcc