.nix:
  image: registry.gitlab.com/cynerd/gitlab-ci-nix
  tags:
    - docker
  cache:
    key: "nix"
    paths:
      - ".nix-cache"
  before_script:
    - gitlab-ci-nix-cache-before
  after_script:
    - gitlab-ci-nix-cache-after

stages:
  - build
  - release

backend-build:
  extends: .nix
  stage: build
  script:
    - nix build .#backend

frontend-build:
  extends: .nix
  stage: build
  script:
    - nix build .#frontend

docker-build:
  extends: .nix
  stage: build
  needs:
    - backend-build
    - frontend-build
  artifacts:
    paths:
      - blcc-image.tar.gz
  script:
    - nix build
    - cp result blcc-image.tar.gz

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

release-image:
  image: docker:27.2.1
  stage: release
  needs:
    - docker-build
  tags:
    - dind
  services:
    - docker:27.2.1-dind
  dependencies:
    - docker-build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker load < blcc-image.tar.gz
    - docker tag blcc:latest $IMAGE_TAG
    - docker push $IMAGE_TAG
  
portainer-deploy:
  image: docker:27.2.1
  stage: release
  needs:
    - release-image
  tags:
    - dind
  services:
    - docker:27.2.1-dind
  before_script:
    - apk add jq
    - "export DOCKER_CUSTOM_HEADERS=$(curl -s --header \"Content-Type: application\\json\" --request POST --data '{\"username\":\"$PORTAINER_USERNAME\",\"password\":\"$PORTAINER_PASSWORD\"}' http://haproxy-p.el.nist.gov:9000/api/auth | jq -r .jwt)"
    - docker context create portainer --docker "host=tcp://haproxy-p.el.nist.gov:9000/api/endpoitns/1/docker"
    - docker context switch portainer
  script:
    - docker stack deploy -c portainer-stack.yml --resolve-image changed blcc