.nix:
  image: registry.gitlab.com/cynerd/gitlab-ci-nix
  tags:
    - docker
  cache:
    key: "nix"
    paths:
      - ".nix-cache"
  before_script:
    - gitlab-ci-nix-cache-before
  after_script:
    - gitlab-ci-nix-cache-after

stages:
  - build
  - release

backend-build:
  extends: .nix
  stage: build
  rules:
    - changes: 
      - backend/*
  script:
    - nix build .#backend

frontend-build:
  extends: .nix
  stage: build
  rules:
    - changes:
      - frontend/*
  script:
    - nix build .#frontend

docker-build:
  extends: .nix
  stage: build
  rules:
    - changes:
      - backend/*
      - frontend/*
      - flake.nix
      - flake.lock
  needs:
    - backend-build
    - frontend-build
  artifacts:
    paths:
      - result
  script:
    - nix build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

release-image:
  image: docker:26.1.3
  stage: release
  services:
    - docker:26.1.3-dind
  dependencies:
    - docker-build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker load < result
    - docker tag blcc:latest $IMAGE_TAG
    - docker push $IMAGE_TAG