version: "3.9"
services:
  postgres:
    image: postgres:16.0
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "MvEWFlPGNaEQ8UgcvBpTqk5b3msqM9Fj"
      POSTGRES_DB: BLCC
    ports:
      - "5432:5432"
    networks:
      - default