version: "3.9"
services:
  server:
    build: ./
    image: blcc:latest
    hostname: blcc
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    configs:
      - source: server-config
        target: /.env
    networks:
      - postgres

  postgres:
    image: postgres:16.2
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "MvEWFlPGNaEQ8UgcvBpTqk5b3msqM9Fj"
      POSTGRES_DB: BLCC
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:

configs:
  server-config:
    file: ./.env-backend
