version: "3.9"
services:
  server:
    build: ./
    image: blcc:latest
    hostname: blcc
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16.1
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "MvEWFlPGNaEQ8UgcvBpTqk5b3msqM9Fj"
      POSTGRES_DB: BLCC
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - default