version: "3.9"
services:
  server:
    build: ./
    image: docker.nist.gov:4567/eldst/blcc:latest
    volumes:
      - ./certs:/etc/ssl/certs
    hostname: blcc
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    configs:
      - source: server-config
        target: /.env
    networks:
      - postgres

  postgres:
    image: postgres:16.2
    hostname: postgres
    volumes: 
      - ./dump.pgdata:/etc/dump.pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "MvEWFlPGNaEQ8UgcvBpTqk5b3msqM9Fj"
      POSTGRES_DB: BLCC
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:

configs:
  server-config:
    file: ./.env