version: "3.6"
services:
  server:
    image: docker.nist.gov:4567/lrd/blcc:latest
    hostname: blcc
    depends_on:
      - postgres
    configs:
      - source: blcc-server
        target: /.env
    networks:
      - postgres
      - traefik_net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.http.routers.blcc_router_http.rule=Host(`blcctest.el.nist.gov`)"
        - "traefik.http.routers.blcc_router_http.entrypoints=web"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.blcc_router_http.middlewares=https_redirect"
        - "traefik.http.routers.blcc_router_https.rule=Host(`blcctest.el.nist.gov`)"
        - "traefik.http.routers.blcc_router_https.entrypoints=websecure"
        - "traefik.http.routers.blcc_router_https.tls"
        - "traefik.http.services.blcc_service.loadbalancer.server.port=8080"

  postgres:
    image: dockreg.el.nist.gov/blcc/db:latest
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "MvEWFlPGNaEQ8UgcvBpTqk5b3msqM9Fj"
      POSTGRES_DB: BLCC
    networks:
      - postgres
    #volumes:
    #  - pg_data:/var/lib/postgresql/data
    #  - db_backup:/db_backup
    #  - /DATA/e3/blcc/blcc.pgdata:/blcc.pgdata

networks:
  postgres:
  traefik_net:
    external: true

configs:
  blcc-server:
    external: true

volumes:
  pg_data:
    driver_opts:
      type: none
      device: /DATA/e3/blcc/pg_data
      o: bind
  db_backup:
    driver_opts:
      type: none
      device: /DATA/e3/blcc/db_backup
      o: bind
  #blcc_data:
  #  driver_opts:
  #    type: none
  #    device: /DATA/e3/blcc/blcc.pgdata
  #    o: bind