[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
actix-web = "4.4.1"
actix-files = "0.6.4"
actix-cors = "0.7.0"
env_logger = "0.10.1"
diesel = { version = "2.1.4", features = ["postgres"] }
dotenvy = "0.15.7"
serde = { version = "1.0.192", features = ["derive"] }