[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
actix-web = "4.9.0"
actix-files = "0.6.6"
actix-cors = "0.7.0"
env_logger = "0.11.5"
diesel = { version = "2.2.2", features = ["postgres", "r2d2"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
r2d2 = "0.8.10"
openssl = "*"
postgres = "*"
awc = { version = "3.5.1", features = ["openssl", "tls-openssl"] }
