export enum Country {
    USA = "United States of America",
    Afghanistan = "Afghanistan",
    Albania = "Albania",
    Algeria = "Algeria",
    Andorra = "Andorra",
    Angola = "Angola",
    "Antigua and Barbuda" = "Antigua and Barbuda",
    Argentina = "Argentina",
    Armenia = "Armenia",
    Australia = "Australia",
    Austria = "Austria",
    Azerbaijan = "Azerbaijan",
    Bahamas = "Bahamas",
    Bahrain = "Bahrain",
    Bangladesh = "Bangladesh",
    Barbados = "Barbados",
    Bavaria = "Bavaria",
    Belarus = "Belarus",
    Belgium = "Belgium",
    Belize = "Belize",
    "Benin (Dahomey)" = "Benin (Dahomey)",
    Bolivia = "Bolivia",
    "Bosnia and Herzegovina" = "Bosnia and Herzegovina",
    Botswana = "Botswana",
    Brazil = "Brazil",
    Brunei = "Brunei",
    "Brunswick and Lüneburg" = "Brunswick and Lüneburg",
    Bulgaria = "Bulgaria",
    "Burkina Faso (Upper Volta)" = "Burkina Faso (Upper Volta)",
    Burma = "Burma",
    Burundi = "Burundi",
    "Cabo Verde" = "Cabo Verde",
    Cambodia = "Cambodia",
    Cameroon = "Cameroon",
    Canada = "Canada",
    "Cayman Islands" = "Cayman Islands",
    "Central African Republic" = "Central African Republic",
    "Central American Federation" = "Central American Federation",
    Chad = "Chad",
    Chile = "Chile",
    China = "China",
    Colombia = "Colombia",
    Comoros = "Comoros",
    "Congo Free State" = "Congo Free State",
    "Costa Rica" = "Costa Rica",
    "Cote d’Ivoire (Ivory Coast)" = "Cote d’Ivoire (Ivory Coast)",
    Croatia = "Croatia",
    Cuba = "Cuba",
    Cyprus = "Cyprus",
    Czechia = "Czechia",
    Czechoslovakia = "Czechoslovakia",
    "Democratic Republic of the Congo" = "Democratic Republic of the Congo",
    Denmark = "Denmark",
    Djibouti = "Djibouti",
    Dominica = "Dominica",
    "Dominican Republic" = "Dominican Republic",
    "Duchy of Parma" = "Duchy of Parma",
    "East Germany (German Democratic Republic)" = "East Germany (German Democratic Republic)",
    Ecuador = "Ecuador",
    Egypt = "Egypt",
    "El Salvador" = "El Salvador",
    "Equatorial Guinea" = "Equatorial Guinea",
    Eritrea = "Eritrea",
    Estonia = "Estonia",
    Eswatini = "Eswatini",
    Ethiopia = "Ethiopia",
    Fiji = "Fiji",
    Finland = "Finland",
    France = "France",
    Gabon = "Gabon",
    Gambia = "Gambia",
    Georgia = "Georgia",
    Germany = "Germany",
    Ghana = "Ghana",
    "Grand Duchy of Tuscany" = "Grand Duchy of Tuscany",
    Greece = "Greece",
    Grenada = "Grenada",
    Guatemala = "Guatemala",
    Guinea = "Guinea",
    "Guinea-Bissau" = "Guinea-Bissau",
    Guyana = "Guyana",
    Haiti = "Haiti",
    Hanover = "Hanover",
    "Hanseatic Republics" = "Hanseatic Republics",
    Hawaii = "Hawaii",
    Hesse = "Hesse",
    "Holy See" = "Holy See",
    Honduras = "Honduras",
    Hungary = "Hungary",
    Iceland = "Iceland",
    India = "India",
    Indonesia = "Indonesia",
    Iran = "Iran",
    Iraq = "Iraq",
    Ireland = "Ireland",
    Israel = "Israel",
    Italy = "Italy",
    Jamaica = "Jamaica",
    Japan = "Japan",
    Jordan = "Jordan",
    Kazakhstan = "Kazakhstan",
    Kenya = "Kenya",
    "Kingdom of Serbia/Yugoslavia" = "Kingdom of Serbia/Yugoslavia",
    Kiribati = "Kiribati",
    Korea = "Korea",
    Kosovo = "Kosovo",
    Kuwait = "Kuwait",
    Kyrgyzstan = "Kyrgyzstan",
    Laos = "Laos",
    Latvia = "Latvia",
    Lebanon = "Lebanon",
    Lesotho = "Lesotho",
    "Lew Chew (Loochoo)" = "Lew Chew (Loochoo)",
    Liberia = "Liberia",
    Libya = "Libya",
    Liechtenstein = "Liechtenstein",
    Lithuania = "Lithuania",
    Luxembourg = "Luxembourg",
    Madagascar = "Madagascar",
    Malawi = "Malawi",
    Malaysia = "Malaysia",
    Maldives = "Maldives",
    Mali = "Mali",
    Malta = "Malta",
    "Marshall Islands" = "Marshall Islands",
    Mauritania = "Mauritania",
    Mauritius = "Mauritius",
    "Mecklenburg-Schwerin" = "Mecklenburg-Schwerin",
    "Mecklenburg-Strelitz" = "Mecklenburg-Strelitz",
    Mexico = "Mexico",
    Micronesia = "Micronesia",
    Moldova = "Moldova",
    Monaco = "Monaco",
    Mongolia = "Mongolia",
    Montenegro = "Montenegro",
    Morocco = "Morocco",
    Mozambique = "Mozambique",
    Namibia = "Namibia",
    Nassau = "Nassau",
    Nauru = "Nauru",
    Nepal = "Nepal",
    Netherlands = "Netherlands",
    "New Zealand" = "New Zealand",
    Nicaragua = "Nicaragua",
    Niger = "Niger",
    Nigeria = "Nigeria",
    "North German Confederation" = "North German Confederation",
    "North German Union" = "North German Union",
    "North Macedonia" = "North Macedonia",
    Norway = "Norway",
    Oldenburg = "Oldenburg",
    Oman = "Oman",
    "Orange Free State" = "Orange Free State",
    Pakistan = "Pakistan",
    Palau = "Palau",
    Panama = "Panama",
    "Papal States" = "Papal States",
    "Papua New Guinea" = "Papua New Guinea",
    Paraguay = "Paraguay",
    Peru = "Peru",
    Philippines = "Philippines",
    "Piedmont-Sardinia" = "Piedmont-Sardinia",
    Poland = "Poland",
    Portugal = "Portugal",
    Qatar = "Qatar",
    "Republic of Genoa" = "Republic of Genoa",
    "Republic of Korea (South Korea)" = "Republic of Korea (South Korea)",
    "Republic of the Congo" = "Republic of the Congo",
    Romania = "Romania",
    Russia = "Russia",
    Rwanda = "Rwanda",
    "Saint Kitts and Nevis" = "Saint Kitts and Nevis",
    "Saint Lucia" = "Saint Lucia",
    "Saint Vincent and the Grenadines" = "Saint Vincent and the Grenadines",
    Samoa = "Samoa",
    "San Marino" = "San Marino",
    "Sao Tome and Principe" = "Sao Tome and Principe",
    "Saudi Arabia" = "Saudi Arabia",
    "Schaumburg-Lippe" = "Schaumburg-Lippe",
    Senegal = "Senegal",
    Serbia = "Serbia",
    Seychelles = "Seychelles",
    "Sierra Leone" = "Sierra Leone",
    Singapore = "Singapore",
    Slovakia = "Slovakia",
    Slovenia = "Slovenia",
    "Solomon Islands" = "Solomon Islands",
    Somalia = "Somalia",
    "South Africa" = "South Africa",
    "South Sudan" = "South Sudan",
    Spain = "Spain",
    "Sri Lanka" = "Sri Lanka",
    Sudan = "Sudan",
    Suriname = "Suriname",
    Sweden = "Sweden",
    Switzerland = "Switzerland",
    Syria = "Syria",
    Tajikistan = "Tajikistan",
    Tanzania = "Tanzania",
    Thailand = "Thailand",
    "Timor-Leste" = "Timor-Leste",
    Togo = "Togo",
    Tonga = "Tonga",
    "Trinidad and Tobago" = "Trinidad and Tobago",
    Tunisia = "Tunisia",
    Turkey = "Turkey",
    Turkmenistan = "Turkmenistan",
    Tuvalu = "Tuvalu",
    "Two Sicilies" = "Two Sicilies",
    Uganda = "Uganda",
    Ukraine = "Ukraine",
    "United Arab Emirates" = "United Arab Emirates",
    "United Kingdom" = "United Kingdom",
    Uruguay = "Uruguay",
    Uzbekistan = "Uzbekistan",
    Vanuatu = "Vanuatu",
    Venezuela = "Venezuela",
    Vietnam = "Vietnam",
    Württemberg = "Württemberg",
    Yemen = "Yemen",
    Zambia = "Zambia",
    Zimbabwe = "Zimbabwe",
}

export enum State {
    AL = "AL",
    AK = "AK",
    AZ = "AZ",
    AR = "AR",
    CA = "CA",
    CO = "CO",
    CT = "CT",
    DE = "DE",
    FL = "FL",
    GA = "GA",
    HI = "HI",
    ID = "ID",
    IL = "IL",
    IN = "IN",
    IA = "IA",
    KS = "KS",
    KY = "KY",
    LA = "LA",
    ME = "ME",
    MD = "MD",
    MA = "MA",
    MI = "MI",
    MN = "MN",
    MS = "MS",
    MO = "MO",
    MT = "MT",
    NE = "NE",
    NV = "NV",
    NH = "NH",
    NJ = "NJ",
    NM = "NM",
    NY = "NY",
    NC = "NC",
    ND = "ND",
    OH = "OH",
    OK = "OK",
    OR = "OR",
    PA = "PA",
    RI = "RI",
    SC = "SC",
    SD = "SD",
    TN = "TN",
    TX = "TX",
    UT = "UT",
    VT = "VT",
    VA = "VA",
    WA = "WA",
    WV = "WV",
    WI = "WI",
    WY = "WY",
    DC = "DC",
    AS = "AS",
    BI = "BI",
    GU = "GU",
    JI = "JI",
    JA = "JA",
    KR = "KR",
    MW = "MW",
    NI = "NI",
    PI = "PI",
    WK = "WK",
    NO = "NO",
    PR = "PR",
    VI = "VI",
}

const stateToAbbreviation: { [key: string]: State } = {
    Alabama: State.AL,
    Alaska: State.AK,
    "American Samoa": State.AS,
    Arizona: State.AZ,
    Arkansas: State.AR,
    California: State.CA,
    Colorado: State.CO,
    Connecticut: State.CT,
    Delaware: State.DE,
    "District of Columbia": State.DC,
    Florida: State.FL,
    Georgia: State.GA,
    Guam: State.GU,
    Hawaii: State.HI,
    Idaho: State.ID,
    Illinois: State.IL,
    Indiana: State.IN,
    Iowa: State.IA,
    Kansas: State.KS,
    Kentucky: State.KY,
    Louisiana: State.LA,
    Maine: State.ME,
    Maryland: State.MD,
    Massachusetts: State.MA,
    Michigan: State.MI,
    Minnesota: State.MN,
    Mississippi: State.MS,
    Missouri: State.MO,
    Montana: State.MT,
    Nebraska: State.NE,
    Nevada: State.NV,
    "New Hampshire": State.NH,
    "New Jersey": State.NJ,
    "New Mexico": State.NM,
    "New York": State.NY,
    "North Carolina": State.NC,
    "North Dakota": State.ND,
    Ohio: State.OH,
    Oklahoma: State.OK,
    Oregon: State.OR,
    Pennsylvania: State.PA,
    "Puerto Rico": State.PR,
    "Rhode Island": State.RI,
    "South Carolina": State.SC,
    "South Dakota": State.SD,
    Tennessee: State.TN,
    Texas: State.TX,
    Utah: State.UT,
    Vermont: State.VT,
    "Virgin Islands": State.VI,
    Virginia: State.VA,
    Washington: State.WA,
    "West Virginia": State.WV,
    Wisconsin: State.WI,
    Wyoming: State.WY,
};

export { stateToAbbreviation };
